# Generated by Django 3.0.4 on 2020-05-12 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('number', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benificiary_name', models.TextField(max_length=100)),
                ('rationcard_number', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0][0-9]{11}')])),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='[1-9][0-9]{9}')])),
                ('entry_made_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('number', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0][0-9]{11}')])),
                ('number_raw', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0][0-9]{11}')])),
                ('headoffamily', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('name', models.TextField(db_index=True, max_length=128)),
                ('number', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Circle')),
            ],
        ),
        migrations.CreateModel(
            name='FPS',
            fields=[
                ('number', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('address', models.TextField()),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Circle')),
            ],
        ),
    ]
