# Generated by Django 3.0.4 on 2020-05-12 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleNumber',
            fields=[
                ('circle_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('circle_name', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FPShop',
            fields=[
                ('fpshop_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('fpshop_name', models.TextField()),
                ('fpshop_address', models.TextField()),
                ('circlenumber_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CircleNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_type', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('rationcard_number', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('familyhead_name', models.TextField(max_length=100)),
                ('shop_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FPShop')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('locality_name', models.TextField(max_length=500, primary_key=True, serialize=False)),
                ('locality_number', models.IntegerField(blank=True)),
                ('circlenumber_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CircleNumber')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.TextField(max_length=500, primary_key=True, serialize=False)),
                ('collector_name', models.TextField(blank=True, max_length=100)),
                ('shop_key', models.IntegerField(blank=True)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('locality_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Locality')),
                ('rationcard_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RationCard')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FPShop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
