# Generated by Django 3.0.4 on 2020-05-12 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='entry_made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='fps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FPS'),
        ),
        migrations.AddField(
            model_name='collection',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Locality'),
        ),
        migrations.AddField(
            model_name='collection',
            name='rationcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RationCard'),
        ),
    ]
