# Generated by Django 3.0.4 on 2020-05-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FPScreds',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.TextField(default='FPSUser'),
        ),
    ]
